README.md
src/tmtccmd/core/definitions.py
src/tmtccmd/defaults/globals_setup.py
src/tmtccmd/pus_tc/service_8_functional_cmd.py

- PUS Service 11 added
- README improvements

Small update

---

src/tmtccmd/pus_tc/base.py
src/tmtccmd/pus_tm/base.py
src/tmtccmd/tmtc/spacepacket.py

Refactored and improved code for Space Packets as preparation for CFDP (CCSDS File Delivery Protocol) packet creation which will build on Space Packets.

Updates from SOURCE branch

---

src/tmtccmd/__init__.py

new revision for version bump

---

src/tmtccmd/__init__.py
src/tmtccmd/com_if/tcpip_udp_com_if.py

Important bugfix, which can cause crashes

Bugfix for UDP communication interface

---

src/tmtccmd/config/globals.py
src/tmtccmd/ecss/tm.py

- Increased robustness against invalid communication interface keys
- Added function to extract the service ID from a raw PUS packet

Update from SOURCE branch

---

src/tmtccmd/com_if/serial_com_if.py
src/tmtccmd/com_if/serial_utilities.py
src/tmtccmd/utility/json_handler.py

Added a feature to specify a hint for a serial device, because COM ports can change but the serial device name usually doesn't.

Serial port hint feature

---

src/tmtccmd/cfdp/conf.py
src/tmtccmd/cfdp/definitions.py
src/tmtccmd/cfdp/lv.py
src/tmtccmd/cfdp/pdu/ack.py
src/tmtccmd/cfdp/pdu/eof.py
src/tmtccmd/cfdp/pdu/file_directive.py
src/tmtccmd/cfdp/pdu/finished.py
src/tmtccmd/cfdp/pdu/header.py
src/tmtccmd/cfdp/pdu/metadata.py
src/tmtccmd/cfdp/tlv.py
src/tmtccmd/config/args.py
src/tmtccmd/core/backend.py
src/tmtccmd/tm/service_3_base.py
src/tmtccmd/tm/service_3_housekeeping.py
src/tmtccmd/utility/tmtc_printer.py

Implementation continued. Currently implemented classes:
- TLV field class
- LV field class
- PDU classes for 
- Metadata
- ACK
- EOF
- Finished

CFDP implementation continued

---

src/tests/test_global_manager.py
src/tests/test_printer.py
src/tmtccmd/config/globals.py
src/tmtccmd/pus/obj_id.py
src/tmtccmd/tm/definitions.py
src/tmtccmd/tm/service_1_verification.py
src/tmtccmd/tm/service_3_housekeeping.py
src/tmtccmd/tm/service_5_event.py
src/tmtccmd/utility/tmtc_printer.py

- Various bugfixes, improvements and linter fixes for updated TM handling

Update from SOURCE

---

src/tmtccmd/__init__.py

- Bump version number to v1.8.0

v1.8.0 Version Number Bump

---

src/tmtccmd/tc/service_8_functional_cmd.py
src/tmtccmd/tm/service_1_verification.py
src/tmtccmd/tm/service_8_functional_cmd.py
src/tmtccmd/utility/tmtc_printer.py

- Bugfixes for Service 1 telemetry unpacking
- Some other smaller bugfixes

Update from EIVE

---

src/tmtccmd/com_if/tcpip_tcp_com_if.py
src/tmtccmd/tc/service_200_mode.py

Simplified the TCP client by keeping the connection opened instead of closing it after ever transaction

Simplified TCP client

---

src/tmtccmd/config/args.py
src/tmtccmd/config/globals.py

- This bugfix should cause the core to prompt the service again if no service argument is specified for the CLI mode

Bugfix Service Prompt

---

src/tmtccmd/com_if/serial_utilities.py
src/tmtccmd/com_if/tcpip_utilities.py

Default option is specified more clearly now

improved prompt handling

---

CHANGELOG.md
src/tmtccmd/config/__init__.py
src/tmtccmd/config/definitions.py
src/tmtccmd/config/globals.py
src/tmtccmd/config/hook.py
src/tmtccmd/tm/service_3_base.py
src/tmtccmd/tm/service_3_housekeeping.py
src/tmtccmd/utility/tmtc_printer.py

- Also added bugfix for HK packet handling
- Added some first useful re-exports for `tmtccmd.config`

Improved API for handling Service 3 and Service 8 packets

---

CHANGELOG.md
README.md
setup.cfg
src/tmtccmd/config/args.py

- Add `prompt-toolkit` dependency
- Add auto-complete for selecting service and op-code

Added CLI auto-complete features

---

src/tmtccmd/config/args.py

Service and Op-Code Sel Output format

---

src/tmtccmd/config/args.py

Made Argument Parser handling for service and Op-Code more robust

Important bugfixes

---

src/tmtccmd/pus/obj_id.py
src/tmtccmd/utility/tmtc_printer.py

service 8 object id printout

---

src/tmtccmd/core/globals_manager.py

- Some more configurability for this lock

Globals lock bugfix

---

src/tmtccmd/core/backend.py
src/tmtccmd/core/frontend.py
src/tmtccmd/runner.py

- Enable one-shot operation in GUI mode

some fixes for GUI mode

---

src/tmtccmd/com_if/tcpip_tcp_com_if.py
src/tmtccmd/core/backend.py
src/tmtccmd/core/frontend.py

- TCP Client tweaks which allow disconnect/connect sequences in GUI
- Frontend bugfixes for Communication Interface Handling

GUI fixes and TCP server tweaks

---

src/tmtccmd/com_if/tcpip_tcp_com_if.py
src/tmtccmd/sendreceive/sequential_sender_receiver.py

#70 broke tcp/ip handling
#65 had an infinite loop in `SequentialCommandSenderReceiver.__handle_tc_sending()`
#65 still had debug output

some regressions and debugging code from previous PRs

---

src/tmtccmd/config/definitions.py
src/tmtccmd/core/backend.py
src/tmtccmd/runner.py
src/tmtccmd/sendreceive/tm_listener.py
src/tmtccmd/tc/pus_3_fsfw_hk.py
src/tmtccmd/tm/pus_17_test.py
src/tmtccmd/utility/tmtc_printer.py

- Some improvements for new continous mode support
- Minor PUS17 bugfix
- A few new API function for the HK TC module

Update from EIVE fork

---

tmtccmd/tc/queue.py

Removed wrong Optional Type hint from DefaultPusQueueHelper queue_wrapper

Removed wrong type hint
